sonar.projectKey=linestr_Projeto-QS-Emprestimo-Ferramentas
sonar.organization=linestr
sonar.sources=Emprestimo-de-Ferramentas-master/Emprestimo-de-Ferramentas-master/src/main/java
sonar.tests=testes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/visao/**,**/principal/**